version: '3.8'

services:
  ponger_1:
    build:
      context: .
      dockerfile: ./internal/servicemanager/testhelpers/dummyservice/ponger/Dockerfile
    environment:
      - SERVER_PORT=8080
    ports:
      - "8081:8080"

  ponger_2:
    build:
      context: .
      dockerfile: ./internal/servicemanager/testhelpers/dummyservice/ponger/Dockerfile
    environment:
      - SERVER_PORT=8080
    ports:
      - "8082:8080"

  ponger_3:
    build:
      context: .
      dockerfile: ./internal/servicemanager/testhelpers/dummyservice/ponger/Dockerfile
    environment:
      - SERVER_PORT=8080
    ports:
      - "8083:8080"

  balancer:
    build:
      context: .
      dockerfile: ./cmd/balancer/Dockerfile
    environment:
#      - CLIENT_LIMITS="vasya=60,petya=1.5"
      - CONFIG_PATH=compose.config.json
    volumes:
      - ./compose.config.json:/app/compose.config.json
    ports:
      - "8080:8080"